Changes Reflecting BAG3 Open Sourcing Updates
google/skywater-pdk-libs-sky130_bag3_pr pull request #8
Opened 2023-05-04 23:03 UTC by FeliciaG

Changes have been made to reflect updates used in June 2022 and December 2022 tapeouts. This update is compatible with the newly released BAG3++, which is has a completely publicly available codebase.

2023-05-08 18:04 UTC, mithro reviewed
Could you fix the copyright header removals / changes?

2023-05-09 09:11 UTC, FeliciaG commented
The copyright headers should be fixed now, please let me know if there are other issues.

2023-05-09 16:16 UTC, mithro commented on OA/BAG_prim/cdsinfo.tag
>  # Copyright 2019-2021 SkyWater PDK Authors
This file is still be weirdly modified.

2023-05-09 16:18 UTC, mithro commented on README.md
> -# BAG (BAG AMS Generator) Primitives Library for [SKY130](https://github.com/google/skywater-pdk)
Could we keep this header?

2023-05-09 16:18 UTC, mithro commented on README.md
> -This repository contains the required primitives to use the BAG3 framework with
Could we keep this description?

2023-05-09 16:19 UTC, mithro commented on install.sh
> +	         ".simrc"
Random unneeded change?

2023-05-09 16:19 UTC, mithro commented on install.sh
> +#!/usr/bin/env bash
This line seems wrong?

2023-05-09 16:19 UTC, mithro commented on install.sh
> +#!/bin/bash
Can we keep the hashbang as previous?

2023-05-09 16:24 UTC, mithro requested changes
Getting pretty close. There are still some fixes needed.

 * The README.md needs to keep the old content. Your new additions are fine though.
 * A few files have been slightly mangled when fixing the copyright header.
 * Duplicate `# -*- coding: utf-8 -*-` lines (needs to be the second line in the file).
 * Some files still missing copyright headers.

2023-05-11 06:40 UTC, FeliciaG commented
Sorry for the slow turnaround. I fixed: 

- the README to include the old content
- mangled copyright headers
- Duplicated `# -*- coding: utf-8 -*- ` lines
- missing copyright headers (I think I hit all of them, but if you catch more missing ones, please let me know)

2023-05-15 15:54 UTC, merged

2023-05-15 16:20 UTC, mithro commented
@FeliciaG - I have merged this pull request but there are a couple of issues I identified, see
 * #9 
 * #10 
 * #11

2023-05-15 16:24 UTC, mithro commented
@FeliciaG - I also invited you to this repository so that these issues can be assigned to you.